"""init

Revision ID: 848c2e9e962d
Revises: 3e5b4e6b35ad
Create Date: 2025-06-01 01:27:44.939597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848c2e9e962d'
down_revision: Union[str, None] = '3e5b4e6b35ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LongTour')
    op.drop_table('OneDayTour')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OneDayTour',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.VARCHAR(), nullable=False),
    sa.Column('fio', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('operator', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('paydate', sa.DATE(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('LongTour',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('customer', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=False),
    sa.Column('p_count', sa.VARCHAR(), nullable=False),
    sa.Column('bus', sa.VARCHAR(), nullable=False),
    sa.Column('locations', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
